// <auto-generated />
using System;
using EDennis.AspNetUtils.Tests.MvcSample;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EDennis.AspNetUtils.Tests.MvcSample.Migrations.Hits
{
    [DbContext(typeof(HitsContext))]
    [Migration("20230507080235_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<int>("seqArtist");

            modelBuilder.HasSequence<int>("seqSong");

            modelBuilder.Entity("EDennis.AspNetUtils.Tests.MvcSample.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("(NEXT VALUE FOR [seqArtist])");

                    b.Property<bool>("IsSolo")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SysEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("SysEnd");

                    b.Property<Guid>("SysGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SysStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("SysStart");

                    b.Property<string>("SysUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Artist", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("Artist", "dbo_history");
                                ttb
                                    .HasPeriodStart("SysStart")
                                    .HasColumnName("SysStart");
                                ttb
                                    .HasPeriodEnd("SysEnd")
                                    .HasColumnName("SysEnd");
                            }));

                    b.HasData(
                        new
                        {
                            Id = -1,
                            IsSolo = false,
                            Name = "Beatles",
                            SysGuid = new Guid("00000001-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = -2,
                            IsSolo = true,
                            Name = "Billy Joel",
                            SysGuid = new Guid("00000002-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = -3,
                            IsSolo = false,
                            Name = "Led Zeppelin",
                            SysGuid = new Guid("00000003-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = -4,
                            IsSolo = false,
                            Name = "Eagles",
                            SysGuid = new Guid("00000004-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = -5,
                            IsSolo = true,
                            Name = "Marvin Gaye",
                            SysGuid = new Guid("00000005-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = -6,
                            IsSolo = false,
                            Name = "Queen",
                            SysGuid = new Guid("00000006-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = -7,
                            IsSolo = true,
                            Name = "Aretha Franklin",
                            SysGuid = new Guid("00000007-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = -8,
                            IsSolo = false,
                            Name = "Aerosmith",
                            SysGuid = new Guid("00000008-0000-0000-0000-000000000008")
                        });
                });

            modelBuilder.Entity("EDennis.AspNetUtils.Tests.MvcSample.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("(NEXT VALUE FOR [seqSong])");

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SysEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("SysEnd");

                    b.Property<Guid>("SysGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SysStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("SysStart");

                    b.Property<string>("SysUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.ToTable("Song", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("Song", "dbo_history");
                                ttb
                                    .HasPeriodStart("SysStart")
                                    .HasColumnName("SysStart");
                                ttb
                                    .HasPeriodEnd("SysEnd")
                                    .HasColumnName("SysEnd");
                            }));

                    b.HasData(
                        new
                        {
                            Id = -1,
                            ArtistId = -1,
                            ReleaseDate = new DateTime(1965, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SysGuid = new Guid("00000001-0000-0000-0000-000000000001"),
                            Title = "Yesterday"
                        },
                        new
                        {
                            Id = -2,
                            ArtistId = -1,
                            ReleaseDate = new DateTime(1968, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SysGuid = new Guid("00000002-0000-0000-0000-000000000002"),
                            Title = "Hey Jude"
                        },
                        new
                        {
                            Id = -3,
                            ArtistId = -2,
                            ReleaseDate = new DateTime(1973, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SysGuid = new Guid("00000003-0000-0000-0000-000000000003"),
                            Title = "Piano Man"
                        },
                        new
                        {
                            Id = -4,
                            ArtistId = -2,
                            ReleaseDate = new DateTime(1978, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SysGuid = new Guid("00000004-0000-0000-0000-000000000004"),
                            Title = "My Life"
                        },
                        new
                        {
                            Id = -5,
                            ArtistId = -3,
                            ReleaseDate = new DateTime(1975, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SysGuid = new Guid("00000005-0000-0000-0000-000000000005"),
                            Title = "Kashmir"
                        },
                        new
                        {
                            Id = -6,
                            ArtistId = -3,
                            ReleaseDate = new DateTime(1979, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SysGuid = new Guid("00000006-0000-0000-0000-000000000006"),
                            Title = "Fool in the Rain"
                        },
                        new
                        {
                            Id = -7,
                            ArtistId = -4,
                            ReleaseDate = new DateTime(1976, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SysGuid = new Guid("00000007-0000-0000-0000-000000000007"),
                            Title = "Hotel California"
                        },
                        new
                        {
                            Id = -8,
                            ArtistId = -4,
                            ReleaseDate = new DateTime(1972, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SysGuid = new Guid("00000008-0000-0000-0000-000000000008"),
                            Title = "Take It Easy"
                        },
                        new
                        {
                            Id = -9,
                            ArtistId = -5,
                            ReleaseDate = new DateTime(1967, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SysGuid = new Guid("00000009-0000-0000-0000-000000000009"),
                            Title = "I Heard It Through the Grapevine"
                        },
                        new
                        {
                            Id = -10,
                            ArtistId = -5,
                            ReleaseDate = new DateTime(1971, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SysGuid = new Guid("00000010-0000-0000-0000-000000000010"),
                            Title = "What's Going On"
                        },
                        new
                        {
                            Id = -11,
                            ArtistId = -6,
                            ReleaseDate = new DateTime(1975, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SysGuid = new Guid("00000011-0000-0000-0000-000000000011"),
                            Title = "Bohemian Rhapsody"
                        },
                        new
                        {
                            Id = -12,
                            ArtistId = -6,
                            ReleaseDate = new DateTime(1977, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SysGuid = new Guid("00000012-0000-0000-0000-000000000012"),
                            Title = "We Will Rock You"
                        },
                        new
                        {
                            Id = -13,
                            ArtistId = -7,
                            ReleaseDate = new DateTime(1967, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SysGuid = new Guid("00000013-0000-0000-0000-000000000013"),
                            Title = "Respect"
                        },
                        new
                        {
                            Id = -14,
                            ArtistId = -7,
                            ReleaseDate = new DateTime(1968, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SysGuid = new Guid("00000014-0000-0000-0000-000000000014"),
                            Title = "Think"
                        },
                        new
                        {
                            Id = -15,
                            ArtistId = -8,
                            ReleaseDate = new DateTime(1973, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SysGuid = new Guid("00000015-0000-0000-0000-000000000015"),
                            Title = "Dream On"
                        },
                        new
                        {
                            Id = -16,
                            ArtistId = -8,
                            ReleaseDate = new DateTime(1975, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SysGuid = new Guid("00000016-0000-0000-0000-000000000016"),
                            Title = "Sweet Emotion"
                        });
                });

            modelBuilder.Entity("EDennis.AspNetUtils.Tests.MvcSample.Song", b =>
                {
                    b.HasOne("EDennis.AspNetUtils.Tests.MvcSample.Artist", "Artist")
                        .WithMany("Songs")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("EDennis.AspNetUtils.Tests.MvcSample.Artist", b =>
                {
                    b.Navigation("Songs");
                });
#pragma warning restore 612, 618
        }
    }
}
