// <auto-generated />
using System;
using EDennis.AspNetUtils;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EDennis.AspNetUtils.Migrations
{
    [DbContext(typeof(AppUserRolesContext))]
    [Migration("20230509223414_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<int>("seqAppRole");

            modelBuilder.HasSequence<int>("seqAppUser");

            modelBuilder.Entity("EDennis.AspNetUtils.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("(NEXT VALUE FOR [seqAppRole])");

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SysEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("SysEnd");

                    b.Property<Guid>("SysGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SysStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("SysStart");

                    b.Property<string>("SysUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppRole", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("AppRole", "dbo_history");
                                ttb
                                    .HasPeriodStart("SysStart")
                                    .HasColumnName("SysStart");
                                ttb
                                    .HasPeriodEnd("SysEnd")
                                    .HasColumnName("SysEnd");
                            }));

                    b.HasData(
                        new
                        {
                            Id = -1,
                            RoleName = "IT",
                            SysGuid = new Guid("00000001-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = -2,
                            RoleName = "admin",
                            SysGuid = new Guid("00000002-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = -3,
                            RoleName = "user",
                            SysGuid = new Guid("00000003-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = -4,
                            RoleName = "readonly",
                            SysGuid = new Guid("00000004-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = -5,
                            RoleName = "disabled",
                            SysGuid = new Guid("00000005-0000-0000-0000-000000000005")
                        });
                });

            modelBuilder.Entity("EDennis.AspNetUtils.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("(NEXT VALUE FOR [seqAppUser])");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SysEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("SysEnd");

                    b.Property<Guid>("SysGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SysStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("SysStart");

                    b.Property<string>("SysUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppUser", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("AppUser", "dbo_history");
                                ttb
                                    .HasPeriodStart("SysStart")
                                    .HasColumnName("SysStart");
                                ttb
                                    .HasPeriodEnd("SysEnd")
                                    .HasColumnName("SysEnd");
                            }));

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Role = "IT",
                            SysGuid = new Guid("00000001-0000-0000-0000-000000000001"),
                            UserName = "Starbuck"
                        },
                        new
                        {
                            Id = -2,
                            Role = "admin",
                            SysGuid = new Guid("00000002-0000-0000-0000-000000000002"),
                            UserName = "Maria"
                        },
                        new
                        {
                            Id = -3,
                            Role = "user",
                            SysGuid = new Guid("00000003-0000-0000-0000-000000000003"),
                            UserName = "Darius"
                        },
                        new
                        {
                            Id = -4,
                            Role = "readonly",
                            SysGuid = new Guid("00000004-0000-0000-0000-000000000004"),
                            UserName = "Huan"
                        },
                        new
                        {
                            Id = -5,
                            Role = "disabled",
                            SysGuid = new Guid("00000005-0000-0000-0000-000000000005"),
                            UserName = "Jack"
                        },
                        new
                        {
                            Id = -6,
                            Role = "IT,disabled",
                            SysGuid = new Guid("00000006-0000-0000-0000-000000000006"),
                            UserName = "Watson"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
